sudo: required
dist: trusty

language: node_js

node_js:
  - "8"

cache:
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.npm

script:
  - npm run install:token
  - npm test

after_success:
  - test "${TRAVIS_BRANCH}" = "main" -a "${TRAVIS_PULL_REQUEST}" = "false" && npm publish
