sudo: required
dist: trusty

language: node_js

node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
    - $HOME/.nvm
    - $HOME/.npm

script:
  - npm run install:token
  - npm test

after_success:
  - npm publish
